### ISSUE TITLE
Error when the bag is fitted in the bauble slot.

### ISSUE THREAD

**Issue by LoloElSupremo** [ChloeDawn/BackpackBaubles#4]
Sorry to harass you,
But when I fitted the bag in bauble it took me out of the inventory and I couldn't reopen it.
https://imgur.com/a/gd0T4OK

Crash Report : https://pastebin.com/ig7VxYtY

**Comment by ChloeDawn** [comment]
Does this only happen with my mod present? There is nothing I can see in my code that would cause this crash. Is it reproducible with other bauble items? If so, it may be a conflict between whatever that GUI is and Baubles itself.

**Comment by LoloElSupremo** [comment]
No I have 143 mods present. Maybe it conflicts with the Aether II mod which adds a second inventory interface. (The one we see on the screen)

**Comment by ChloeDawn** [comment]
I have done some testing and the issue is a conflict between Quark's player inventory replacement (when it adds the backpack slots) and Aether II switching to the player inventory. You can reproduce this crash without my mod by equipping the backpack in the usual chestplate slot and switching to and from the Aether II inventory.
```
Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 59, Size: 59
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: Index: 59, Size: 59
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120)
	at net.minecraft.inventory.Container.func_190896_a(Container.java:527)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1191)
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:50)
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:12)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 9 more
```
Due to how roughly implemented Quark's inventory replacement is, I would consider this a bug in Quark and not Aether II. I may look into it and patch it in my mod since Quark for 1.12.2 is "final", but I would still suggest reporting it in case it is considered a significant enough bug for Vazkii to release a hotfix for.

**Comment by LoloElSupremo** [comment]
I had tested the bag without your mod and I had access to the inventory extension without crashing. It was as soon as I put the bag in the bauble with your mod that I had this problem.

**Comment by ChloeDawn** [comment]
I don't know what to tell you; I've confirmed in my own testing that the error can be produced without my mod. It is a conflict between Quark and Aether II, my mod is unrelated to it. The only reason the error can also be reproduced with my mod present is that the error happens when Quark tries to show the backpack inventory.
