### ISSUE TITLE
java.lang.NoClassDefFoundError: dev/sapphic/backpackbaubles/client/BackpackLayer

### ISSUE THREAD

**Issue by aaronhowser1** [ChloeDawn/BackpackBaubles#7]
https://pastebin.com/QX3TFdSj

```java
java.lang.NoClassDefFoundError: dev/sapphic/backpackbaubles/client/BackpackLayer
    at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:50)
    at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:35)
    at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:227)
    at net.minecraft.client.Minecraft.init(Minecraft.java:518)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: dev.sapphic.backpackbaubles.client.BackpackLayer
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 12 more
```

I don't think it's related to #5, removing the `BackpackBaubles-core.jar` file from `/mods/1.12.2/` doesn't fix it.

**Comment by democat3457** [comment]
It is, indeed, the same crash, considering the issue is still open. However, the solution posted in that issue is simply not working, but the issue itself is still valid. The solution was only for updating from one version to the next.

**Comment by aaronhowser1** [comment]
This is a crash on a new instance (importing an export not including the `/mods/1.12/` folder)

**Comment by democat3457** [comment]
I don't see how that affects the fact that it's still the same crash as #5, albeit in a different scenario.

**Comment by ChloeDawn** [comment]
It is indeed related. There seems to be an issue wherein the game is unable to load my mod class from whatever classloader the game is using in that context. I haven't had the time to look into it and honestly not sure if I ever will, sorry. This mod was very haphazardly put together and has a variety of issues pertaining to the fact that both Quark and Baubles are poorly written among the parts I need to interact with one another. This project was essentially DOA when I volunteered to create it. I will, however, leave this ticket open, as it's less cluttered context (this message) as to the exact problem now.

**Comment by aaronhowser1** [comment]
That's a huge shame, the Quark Oddities backpack is my favorite and this mod made it 10000x more usable
